### ISSUE TITLE
Reworking landing section

### ISSUE THREAD

**Issue by Xetera** [Xetera/hifumi.io#2]
The landing page is way too hard to read, the hifumi background is nice but the text is very hard to distinguish with such a colorful background.

1. Add a dark overlay and have the buttons and title's z-index on top of it to add more readability
2. Make all the text white
3. Maybe change the background to a darker color?
4 MAYBE rework the subscript member count to be more compact? @pandaxtc

**Comment by jvyden420** [comment]
It would probably look ugly, but you could add a dark transparent overlay (maybe a blur too) behind the text so its more readable.
