### ISSUE TITLE
Site design

### ISSUE THREAD

**Issue by Xetera** [Xetera/hifumi.io#3]
I'm tired of scrolling in #voice-chat for this
![](https://cdn.discordapp.com/attachments/337008404562444291/540388870231949332/hifumi.io.png)

**Comment by jvyden420** [comment]
design has changed alot, should i close since its irrelevant now?

**Comment by pandaxtc** [comment]
*cough* design made by me *cough*

no need to close this, we can place updated designs in this thread + it's useful for discussion ~~like whether or not we should use the anime logo for the title text~~
